### ISSUE TITLE
The navbar need some improvement

### ISSUE THREAD

**Issue by kirtiraj22** [updesh126/ScNMtv#10]
I can improve the navbar by adding some hover effects on it!
so can you assign it to me?

**Comment by updesh126** [comment]
yes do it if you want

**Comment by kirtiraj22** [comment]
can you label it as hacktoberfest?

**Comment by updesh126** [comment]
why not

**Comment by kirtiraj22** [comment]
@updesh126 thanks bro!
I have added the required changes and created a pull request!

**Comment by updesh126** [comment]
Ok

**Comment by updesh126** [comment]
can you toggle navbar in center

**Comment by kirtiraj22** [comment]
> can you toggle navbar in center

@updesh126 Sure mate!

**Comment by kirtiraj22** [comment]
hey @updesh126 am i supposed to change the navbar from 

![Screenshot (40)](https://user-images.githubusercontent.com/83873093/194720376-07d1c113-d6aa-4b04-b9e3-820db4201f45.png)


to 

![HOME NEW MOVIES MOVIES REVIEW SCIENCE LOGIN](https://user-images.githubusercontent.com/83873093/194720390-b7c52c01-48ee-46a2-b971-92687c832c23.png)


will these changes be enough?

**Comment by kirtiraj22** [comment]
hey @updesh126 am i supposed to change the navbar from 
![Screenshot (40)](https://user-images.githubusercontent.com/83873093/194720551-7141e657-9cd9-42a0-b365-83ff52733fe3.png)


to

![Screenshot (41)](https://user-images.githubusercontent.com/83873093/194720557-67023686-7fd6-4fe2-8ba8-e4a7952a90c5.png)

**Comment by updesh126** [comment]
Did you commit it

**Comment by updesh126** [comment]
It look much better

**Comment by kirtiraj22** [comment]
not yet

> Did you commit it

can i create a pr for the above changes?

**Comment by updesh126** [comment]
why not

**Comment by kirtiraj22** [comment]
> why not

done!
