### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by abhie16** [updesh126/ScNMtv#24]
I would like to add dark mode on website

**Comment by updesh126** [comment]
add it if you want

**Comment by updesh126** [comment]
did you change the color of nav bar

**Comment by abhie16** [comment]
No

**Comment by updesh126** [comment]
Ok

**Comment by updesh126** [comment]
nothing has change yet

**Comment by abhie16** [comment]
[screencast-127.0.0.1_5500-2022.10.18-07_56_38.webm](https://user-images.githubusercontent.com/95357648/196321139-86d6144d-c4a3-46ce-8f96-b8a32f592586.webm)

It is working in my device. With same code.

**Comment by updesh126** [comment]
Ok let's check it , thanks a lot.

**Comment by abhie16** [comment]
no prblm buddy , close this issue as cmplted
